### ISSUE TITLE
Doesn´t work on Ubuntu 16.04.4 LTS

### ISSUE THREAD

**Issue by hyperpac** [sidtechnical/hakuna-metadata-1#7]
python tool.py produces this output:

`No handlers could be found for logger "tldextract"
Traceback (most recent call last):
  File "tool.py", line 336, in <module>
    facebook_df['category_tags']= facebook_df.apply(lambda row: Facebook_URL_Categorizre(row['url_location']), axis=1)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 2357, in __setitem__
    self._set_item(key, value)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 2422, in _set_item
    self._ensure_valid_index(value)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 2404, in _ensure_valid_index
    raise ValueError('Cannot set a frame with no defined index '
ValueError: Cannot set a frame with no defined index and a value that cannot be converted to a Series
`

**Comment by sidtechnical** [comment]
I am not being able to reproduce this error on my Ubuntu 16.04.4 LTS machine. I suspect that it has to do something with your Facebook  browsing history which you don't have I believe?

**Comment by lennartadrian-main** [comment]
I had the same problem but after visiting some sites on facebook, it worked.
